services:
  - type: web
    name: zilliqa-mcp-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd /opt/render/project && node build/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MCP_TRANSPORT
        value: http